# Generated by Django 4.0.8 on 2024-07-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_about_contact_alter_department_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('position', models.CharField(max_length=55)),
                ('about', models.TextField(max_length=255)),
                ('avatar', models.ImageField(upload_to='team')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'team',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'about', 'verbose_name_plural': 'abouts'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
    ]
