# Generated by Django 4.0.8 on 2024-07-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_team_alter_about_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
    ]
