# Generated by Django 4.0.8 on 2024-07-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_team_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(upload_to='media/team'),
        ),
    ]
