# Generated by Django 4.0.8 on 2024-07-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_og'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Home Text',
                'verbose_name_plural': 'Home Texts',
            },
        ),
    ]
